sudo: true
matrix:
  include:
    - language: node_js
      node_js: "8.9.4"
      env: 
        - JOB="JAVA"
      before_install:
        - chmod +x mvnw && chmod +x .travis-deploy-heroku.sh
      install:
        - ./mvnw clean package -Pbuild-ui
      script: ./.travis-deploy-heroku.sh 
    - language: android
      node_js: "8.x"
      env: 
        - JOB="ANDROID"
      android:
          components:
            - build-tools-27.0.3
            - tools
            - platform-tools
            - android-26
            - extra-android-m2repository
            - extra-google-m2repository
      before_install:
          - echo yes | sdkmanager "ndk-bundle"
          - echo yes | sdkmanager "cmake;3.6.4111459"
          - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
          - export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL="https://services.gradle.org/distributions/gradle-4.4-all.zip"          
          - mkdir "$ANDROID_HOME/licenses" || true		
          - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"		
          - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install -y nodejs
      install:
          - cd ./cordova-app/app && npm install && npm run preconfig && npm run build
      script: curl https://$APPETIZE_TOKEN@api.appetize.io/v1/apps/$APPETIZE_PUBLIC_KEY -F "file=@platforms/android/build/outputs/apk/android-debug.apk" -F "platform=android"

